[MCC-772940] Reorganize for compatibility
mdsol/mauth-client-dotnet pull request #82
Opened 2021-05-26 05:06 UTC by lschreck-mdsol

This PR eliminates the libraries multitargeting and sets every library to the closest target framework as possible without losing functionality.

In order to be simpler and straightforward, the unit test project also got separated by target framework/library.

Currently NRTM until the Artifactory credentials getting sorted out.

@mdsol/enablement-dotnet

2021-05-26 11:39 UTC, Jman420 requested changes
This PR contains secrets which must be invalidated.

2021-05-26 12:31 UTC, prajon84 commented
cc: @lyndon-gabriel

2021-05-26 14:04 UTC, prajon84 commented on version.props
> +    <Version>5.1.3</Version>
Since `version` is bumped. Needs `CHANGELOG.md` also update ?

2021-05-27 01:12 UTC, lschreck-mdsol commented on version.props
> +    <Version>5.1.3</Version>
You are right, added d4013aa

2021-05-27 16:25 UTC, lyndon-gabriel commented on src/Medidata.MAuth.Core/HttpRequestMessageExtensions.cs
> +                request.Content.ReadAsStreamAsync().GetAwaiter().GetResult().CopyTo(memoryStream);
This can cause performance issues. The Sync API was introduced in .NET 5 which is why we multi targeted. AFAIK This will allocate 2 threads which was caused major performance issue for RaveEDC in the past.

2021-05-28 00:49 UTC, lschreck-mdsol commented on src/Medidata.MAuth.Core/HttpRequestMessageExtensions.cs
> +                request.Content.ReadAsStreamAsync().GetAwaiter().GetResult().CopyTo(memoryStream);
As covering .NET Standard 2.0 (i.e. .NET Framework 4.6.1) and .NET 5.0 at the same time supposedly won't cause any dependency issues (for now) I restored the multitargeting for this case. 9c0e5c6

2021-06-01 13:17 UTC, prajon84 commented on src/Medidata.MAuth.Core/MAuthCore.cs
>  }
new line

2021-06-01 13:17 UTC, prajon84 commented on tests/Directory.Build.props
> +</Project>
New line.

2021-06-01 13:30 UTC, jfeltesse-mdsol reviewed
The artifactory secrets should be set but instead of a "password", the api key should have been set as `ARTIFACTORY_API_KEY`.

2021-06-03 13:08 UTC, Jman420 approved these changes
Updated file names are sufficient.  Thanks guys, looks good to me.

2021-06-03 14:10 UTC, rkorneev commented on .github/workflows/publish.yaml
> +          API_KEY: ${{ format('{0}:{1}', secrets.ARTIFACTORY_USERNAME, secrets.ARTIFACTORY_API_KEY) }}
We have org level secret `ARTIFACTORY_PASSWORD` (paired with `ARTIFACTORY_USERNAME`), but not `ARTIFACTORY_API_KEY`.
So `ARTIFACTORY_API_KEY` is not going to work unless you override on repo level

2021-06-03 15:20 UTC, jfeltesse-mdsol commented on .github/workflows/publish.yaml
> +          API_KEY: ${{ format('{0}:{1}', secrets.ARTIFACTORY_USERNAME, secrets.ARTIFACTORY_API_KEY) }}
That's what we thought and the reason we had artifactory password, like the other repos using GHA in our org. Turns out, org level secrets are only set for private repos. 
We had a long thread on Slack about that but bottom line, is we created a new artifactory account and had the credentials set for username and api key, hence the changes here.

2021-06-03 18:52 UTC, danielloganking commented on src/Medidata.MAuth.Core/HttpRequestMessageExtensions.cs
> +            using var memoryStream = new MemoryStream();
Doesn't this require us to specify the LangVersion as 8 or greater as "bracket-less using statements" is a feature of C# not of any particular .NET version?

[Relevant doc](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement)

2021-06-03 18:54 UTC, danielloganking commented on src/Medidata.MAuth.Core/MAuthCoreV2.cs
> +
NIT: no need for new line to start the method

2021-06-03 19:02 UTC, danielloganking commented on tests/Medidata.MAuth.Tests.Common/Infrastructure/AssertSigningHandler.cs
> -#endif
Is this no longer needed for synchronous sending support?

2021-06-03 19:03 UTC, rkorneev commented on .github/workflows/publish.yaml
> +          API_KEY: ${{ format('{0}:{1}', secrets.ARTIFACTORY_USERNAME, secrets.ARTIFACTORY_API_KEY) }}
I see, thank you for explaining that.

2021-06-03 19:05 UTC, danielloganking commented on tests/Medidata.MAuth.CoreTests/MAuthAuthenticatorTests.cs
> -                ));
Why are we removing this check?

2021-06-04 00:22 UTC, lschreck-mdsol commented on src/Medidata.MAuth.Core/HttpRequestMessageExtensions.cs
> +            using var memoryStream = new MemoryStream();
The `LangVersion` is set to `latest` [here](https://github.com/mdsol/mauth-client-dotnet/blob/158f171de75c2a06c17e132c2591b05751b50652/Directory.Build.props#L7) which is C#9 currently so this is OK.

2021-06-04 00:27 UTC, lschreck-mdsol commented on tests/Medidata.MAuth.Tests.Common/Infrastructure/AssertSigningHandler.cs
> -#endif
We don't have `Send()` method anymore in the `HttpMessageHandler` under .NET 5.0 and `SendAsync()` can handle the tests without issues so I removed this method.

2021-06-04 00:28 UTC, lschreck-mdsol commented on tests/Medidata.MAuth.CoreTests/MAuthAuthenticatorTests.cs
> -                ));
Unfortunately `FormattedLogValues` is not accessible from the outside anymore in .NET 5.0 (I believe MS changed its visibility to `internal`) so I could not find any sensible way to verify the log message.

2021-06-04 01:40 UTC, danielloganking commented on src/Medidata.MAuth.Core/HttpRequestMessageExtensions.cs
> +            using var memoryStream = new MemoryStream();
👍 I looked for this but missed it 🤦‍♂️

2021-06-04 01:47 UTC, danielloganking commented on tests/Medidata.MAuth.Tests.Common/Infrastructure/AssertSigningHandler.cs
> -#endif
I know that Rave depends on the sync sending but don't really know the details of their needs. Might help to request @lyndon-gabriel to give this a look see. That said if the Sync tests pass it should be fine? 🤷‍♂️

2021-06-04 03:54 UTC, lschreck-mdsol commented on tests/Medidata.MAuth.Tests.Common/Infrastructure/AssertSigningHandler.cs
> -#endif
Yeah, this handler is just asserting the given request so does not contribute to the test act (that is, semantically it's not part of the system under test).

2021-06-07 03:04 UTC, jfeltesse-mdsol commented
Looks like the things that have been pointed out have either been addressed or they can't be fixed so merging for now.

2021-06-07 03:04 UTC, merged