Add time constraint between signature and verification
mdsol/mauth-client-dotnet pull request #96
Opened 2023-03-21 19:32 UTC by eraffel-MDSol

2023-03-21 20:20 UTC, johnduhart commented on src/Medidata.MAuth.Core/MAuthAuthenticator.cs
> +            }
In my Go implementation I put this check before the public key lookup given it's a cheap check.

2023-03-21 20:21 UTC, johnduhart commented
@mdsol/enablement-dotnet

2023-03-21 20:25 UTC, eraffel-MDSol commented on src/Medidata.MAuth.Core/MAuthAuthenticator.cs
> +            }
https://github.com/mdsol/mauth-client-dotnet/pull/96/commits/9ac0976695bf4802e41d9f271211381e259a5456

2023-03-21 21:12 UTC, prajon84 commented on src/Medidata.MAuth.Core/MAuthAuthenticator.cs
> +                return false;
Do we need to throw `TimeOutException` and log error similar to other cases ?

2023-03-22 18:27 UTC, awiesendangermdsol commented on src/Medidata.MAuth.Core/MAuthAuthenticator.cs
> +                return false;
How about a log though? If I had to debug why? Not sure how logging is throughout this library.

2023-03-22 19:22 UTC, prajon84 commented on src/Medidata.MAuth.Core/MAuthAuthenticator.cs
> +                return false;
Yeah at least a logger would be beneficial too.

2023-03-22 23:28 UTC, Jman420 requested changes

2023-03-22 23:28 UTC, Jman420 commented on src/Medidata.MAuth.Core/MAuthAuthenticator.cs
> +                return false;
Agreed on logging.

2023-03-22 23:29 UTC, eraffel-MDSol commented on src/Medidata.MAuth.Core/MAuthAuthenticator.cs
> +                return false;
https://github.com/mdsol/mauth-client-dotnet/pull/96/commits/bf7b84829178af0a6d14df0fe5ed18f5518c751d

2023-03-22 23:29 UTC, Jman420 approved these changes

2023-03-22 23:34 UTC, merged